#!/bin/sh

# -----------------------------------------------------------------------------
# run.sh
# This shell script is auto-generated by the installer to run the Python script using the specified Python executable.
# The following variables are set by the installer:
#   {{PYTHON_EXE}}   - Absolute path to the Python executable.
#   {{MAIN_SCRIPT}}  - Absolute path to the main Python script.
#   {{SCRIPTS_DIR}}  - Absolute path to the scripts directory.
# -----------------------------------------------------------------------------

# Convert the placeholders to absolute paths (if they are relative).
PYTHON_EXE="$(realpath "{{PYTHON_EXE}}")"
MAIN_SCRIPT="$(realpath "{{MAIN_SCRIPT}}")"
SCRIPTS_DIR="$(realpath "{{SCRIPTS_DIR}}")"

# Check if the Python executable exists.
if [ ! -x "$PYTHON_EXE" ]; then
    echo "Error: Python executable not found: $PYTHON_EXE"
    exit 1
fi

# Check if the main Python script exists.
if [ ! -f "$MAIN_SCRIPT" ]; then
    echo "Error: Main Python script not found: $MAIN_SCRIPT"
    exit 1
fi

# Convert backslashes to forward slashes for Python compatibility.
SCRIPTS_DIR_MOD="$SCRIPTS_DIR"
MAIN_SCRIPT_MOD="$MAIN_SCRIPT"

# Set the PYTHONPATH environment variable.
export PYTHONPATH="$SCRIPTS_DIR"

# Construct the inline Python code as a single line.
PY_CODE="import sys; sys.path.insert(0, '$SCRIPTS_DIR_MOD'); sys.argv = ['$MAIN_SCRIPT_MOD'] + sys.argv[1:]; f = open('$MAIN_SCRIPT_MOD', 'r'); code = f.read(); f.close(); globals_dict = {'__file__': '$MAIN_SCRIPT_MOD', '__name__': '__main__'}; exec(compile(code, '$MAIN_SCRIPT_MOD', 'exec'), globals_dict)"

# Execute the Python command and pass all additional arguments.
"$PYTHON_EXE" -c "$PY_CODE" "$@"
PY_EXIT_CODE=$?

if [ $PY_EXIT_CODE -ne 0 ]; then
    echo "Error: Python script execution failed with exit code $PY_EXIT_CODE."
fi

exit $PY_EXIT_CODE
